version: '3.8'

services:
  server:
    container_name: nest-server
    build:
      context: .
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    container_name: postgress
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
